syncpoint/ODIN

- .gitignore
- src/main/main.js
- src/renderer/components/map/Map.js
> Turned off attribution link

- src/main/menu.js
- src/renderer/components/OSD.js
now the whole osd-view can be turned off
>  toggle osd-info

- package-lock.json
- src/main/menu.js
- src/renderer/components/map/Map.js
- src/renderer/components/map/map-visibility.js
> toggle-map-visibility

- electron-builder.yml
> added branded about dialog issue #33

- src/main/projects.js
Added the possibility to pass a command line argument containing the project path.
> Open project on startup

- src/main/bootstrap.js
Since our projects are identified by their unique path we are able to persist all window related settings (size, position) and restore these setting whenever the project gets loaded.
> remember window settings per project

- spectron/UiHelper.js
- spectron/projectManagement.test.js
- src/renderer/components/Management.js
Added tests: create new project, delete project, switch project, rename project, open project manager. Also added the required IDs.
> Project management

- src/renderer/map/Map.js
- src/renderer/map/interactions.js
- src/renderer/map/layers.js
* click feature -> select feature
* shift-click additional feature -> multi-select
* drag point -> move/add point
* option-click point (Window: alt-click) -> delete point
* shift-drag selected feature(s) -> move feature(s)
> 0.6.0/edit geometries

- package-lock.json
- package.json
- src/i18n/de/index.js
- src/i18n/de/web.json
- src/i18n/en/index.js
- src/i18n/en/web.json
- src/i18n/i18next.config.js
- src/main/bootstrap.js
- src/main/main.js
- src/renderer/App.js
- src/renderer/components/Management.js
- src/renderer/i18n.js
- test/renderer/components/management.test.js
ODIN now reacts on language changes triggered by the user. The project management component is fully translated into German and English.
> i18n/react (project management)

- src/renderer/components/Management.js
This PR helps users to identify the selected project in the list.
> mark selected project

- src/renderer/map/layers-interactions.js
- src/renderer/map/layers-util.js
- src/renderer/map/layers.js
- src/renderer/selection.js
- test/renderer/selection-test.js
PR Introduces selection tracking.
Already interfaces with map feature selection.
> 0.6.0/selection

- src/main/ipc/clipboard.js
- src/main/main.js
- src/main/menu/edit-menu.js
- src/renderer/map/layers.js
- src/shared/combinators.js
* Introduce clipboard support: CUT/COPY/PASTE map features.
* ESCAPE key: clears selection
> 0.6.0/clipboard

- src/shared/projects.js
> replaced experimental fs.rmdir with own implementation

- .github/workflows/pre-release-0.6.0-ol.yml
- package.json
* will run on osx-latest
* builds all platform specific binaries
> multi platform build

- src/renderer/components/properties/BoundariesProperties.js
- src/renderer/map/style/line-labels.js
@ThomasHalwax Please have a look at this implementation.
CPU usage seems a little too high while dragging the slider. 
Although updating offset property is already throttled to 75ms.
Maybe you can spot a reason for this.
> #350: boundary - move echelon/unique designations.

- src/renderer/components/palette/FeatureItem.js
- src/renderer/components/palette/FeatureList.js
This PR marks some odd 34 feature as unsupported in feature palette.
> #364: Palette - marked some features as 'unsupported'.

- src/i18n/de/web.json
- src/i18n/en/web.json
- src/renderer/map/interaction/measure/index.js
- src/renderer/map/interaction/measure/style.js
- src/renderer/map/interaction/measure/tools.js
Both measure tool have been greatly improved:
*  show length and bearing for every segment
* show the over all length of the linestring
* begin and end points of the line string are colored green and red
* show the length of every segment of the polygon
* show area and circumference of the polygon
> enhanced measure tools

- src/renderer/map/style/line-labels.js
> changed label styling for PL and CFL

- src/renderer/components/feature-descriptors.json
- src/renderer/map/style/default-style.js
- src/renderer/map/style/fences.js
- src/renderer/map/style/line-geometries.js
- src/renderer/map/style/polygon-geometries.js
- src/renderer/map/style/polygon-style.js
- src/renderer/map/ts.js
The following symbols will be added by the pull request
__obstacle belt__
__obstacle zone__
__obstacle free area__
__obstacle restricted area__
__obstacle abatis__
__mine cluster__
__antitank ditch reinforced with antitank mines__
__antitank wall__
__unspecified fence__
__single fence__
__double fence__
__double apron fence__
__low wire fence__
__high wire fence__
__single concertina__
__double concertina__
__triple strand concertina__
__fortified line__
__air corridor__
__minimum risk route__
__standard-use army aircraft flight route__
__unmanned aircraft route__
__low level transit route__
__radioactive area__
__biological contaminated area__
__chemically contaminated area__
__encirclement__
__fortified area__
> additional symbols

- .github/workflows/release.yml
- electron-builder.yml
- package-lock.json
- package.json
- src/main/bootstrap.js
- src/renderer/App.js
- src/renderer/clipboard.js
- src/renderer/components/ProjectManagement.js
- src/renderer/project/io.js
- src/shared/projects.js
- webpack.config.js
* Electron 16
* electron-builder
* electron-updater
* WebPack-Dev-Server
> updated major versions of core dependencies

- src/renderer/components/feature-descriptors.json
The missing ten symbols from the Emergency Management Symbols/Natural Events area have been added.
> missing natural events

- src/renderer/components/feature-descriptors.json
- src/renderer/components/milsymbol/skkm.js
Implementation of two symbols for cultural property/heritage concernig the Hague Convention,
> two symbols for cultural property-heritage
