syncpoint/ODIN

src/main/menu.js
I have changed the keyboard shortcuts (Windows only) from cntr + alt + "number" to cntr + shift + "number", which works well except for cntr + shift + 0, so the shortcut to reset the filters has been changed to cntr + shift + 9
closes(#42 )
=> changed windows keybindings

src/main/menu/projects-menu.js
when the main windows is closed or minimized the user may still choose "manage projects" from the main menu. This triggers ipcMain.send on an undefined BrowserWindow instance.
The fix checks if the BrowserWindow exists.
=> check if browserWindow exists

src/main/bootstrap.js, src/main/main.js
Electron's default behavior is to quit the app when all windows are closed. The previous version of ODIN consumed the event ```window-all-closed``` and prevented this behavior - at least on OS-X (Darwin).
This PR reestablishes the default on all platforms.
=> quit the app if all windows are closed

src/main/bootstrap.js, src/renderer/App.js
Previews are created in order to allow users to visually choose their projects. Instead of using a timer in the main process this PR uses a react effect to trigger the creation of the preview image.
=> trigger "create preview" from renderer

src/renderer/App.js, src/renderer/project.js
fixes:
#240 (project name not displayed in OSD after rename)
#239 (OSD should show the name of the current project)
=> show the project name in OSD

src/main/menu/edit-menu.js, src/main/menu/menu.js
Common actions like
* select all
* cut
* copy
* paste
* undo
* redo
are only available if the edit menu and the appropriate roles are added to the application.
closes #246
=> add edit menu to support common edit actions

src/main/bootstrap.js
On new projects (without a persisted viewport) we now maximize the window size. Existing projects remember their settings and the viewport will be restored.
Closes #244
=> restore persisted viewport or maximize window size

src/renderer/components/Management.js
In order to allow smaller screen sizes without resulting in a more ugly layout the project management page uses a breakpoint at 1024 px. Screens up to 1024 px uses one column and two rows whereas bigger screens use two columns and one row for the areas "projects" and "details/preview".
=> project management UI with media query

src/main/bootstrap.js, src/renderer/components/Management.js, src/shared/militaryTime.js, src/shared/projects.js
In the project management view projects are now ordered by their last-access time. This time gets updated whenever a user switches to the project.
The last-access time is also set when a user creates a new project. This makes sure that either the recently used or the recently created project is on top of the list.
=> projects are ordered by their lastAccess date

package-lock.json, package.json, src/main/bootstrap.js, src/main/ipc/create-preview.js, src/main/ipc/export-project.js, src/main/ipc/share-project.js, src/renderer/App.js, src/renderer/components/Management.js, src/shared/projects.js, test/renderer/components/management.test.js
Using the project management users can now export and import projects. 
All files within the project folders are added to a zip archive and keep their (folder) structure and names. The projects is stored as a *.odin file but in fact they are regular zip archives.
The user chooses a location in the filesystem and provides a filename (suggestion is $name-of-the-project$.odin). 
The user chooses a *.odin archive. After a successful import the list of projects get refreshed.
ODIN displays a OS Notification in order to tell the user about the success of failure of the import/export operation.
The export notification is clickable and opens the OS filesystem with the exported file selected.
=> import and export ODIN projects

src/main/menu/application-menu.js
During the i18n implementation a NULL value for the application menu was returned on the Win32 platform. This PR fixes the problem.
=> fixed invalid application menu for win32

src/renderer/App.js
App is bound to take on more responsibilities (activity bar, panels and such) in the future.
This PR attempts to add more structure to current App code.
* Combined two one-shot effects
* Removed clean-up function from one-shot effect
* replaced toggleManagementUI() with direct calls to setManagement()
* reduced nesting depth in management/projectPath effect
* added TODOs/FIXMEs for i18n effect (can we move this away from App component?)
* simplified rendering code; moved condition
* updated MUI style creation/usage
=> 0.6.0/app-streamline

src/renderer/map/Map.js, src/renderer/map/basemap.js, src/renderer/map/epsg/epsg.json, src/renderer/map/epsg/index.js, src/renderer/map/sources/index.js, webpack.config.js
This PR allows reading the basemap tile provider settings from the project preferences. It also sets the foundation for basemap management done by the user.
If the there are no preferences the basemap provider will add an OSM TileLayer. It supports OSM, XYZ and WMTS tile sources. In order to test the functionality one can add Austria's ```basemap.at``` to the projects ```preferences.json``` file:
```json
"basemap": {
"type": "WMTS",
"url": "https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml",
"name": "basemap.at HighDPI",
"options": {
"layer": "bmaphidpi",
"matrixSet": "google3857",
"style": "normal"
}
}
```
Since WMTS may provide tiles with a non-Web-Mercator projection it was also required to start adding additional projection definitions. Currently there are 3 definitions included …
=> basemap tile provider from preferences (or defaults to OSM)

package-lock.json, package.json, spectron/hooks.js, spectron/projectManagement.test.js, test/renderer/components/management.test.js
Using mocha for spectron instead of electron-mocha. On Windows there are multiple empty terminals popping up on spectron startup due to issue #60. So setAlwaysOnTop is required as a workaround.
=> Replaced electron mocha

.github/workflows/integrate.yml, .gitignore, package-lock.json, package.json, src/main/main.js, src/shared/config.js
By using the environment variable ```ODIN_LANGUAGE``` the ui language of ODIN can be set. The variable can also be set by creating a file named ```.env``` in the working directory.
All key-value pairs in the file are added to the ```process.env```. 
In order to create language-independent end-to-end tests the i18n framework used supports the language code ```cimode```. In this mode the frameworks returns the i18n key instead of the translation.
=> configure language settings with environment variable

package.json, test/import-test.js, test/register.js
By default babel ignores node_modules. If a test or a tested file imports a module which must be transpiled this will lead to test failures.
=> Babel now transpiles node_modules when running npm test.

src/renderer/map/style/scalebar.css
PR fixes the width of the OL/ScaleBar and makes it align correctly with the MGRS grid. See here for a potential upstream fix: https://github.com/openlayers/openlayers/issues/11118
=> fixed invalid width of the scalebar

src/i18n/de/electron.json, src/i18n/de/web.json, src/i18n/en/electron.json, src/i18n/en/web.json, src/main/bootstrap.js, src/main/ipc/share-project.js, src/main/ipc/share-view.js, src/renderer/components/Activities.js, src/renderer/map/Map.js, src/renderer/map/basemap/tileSources.js, src/renderer/map/share.js
PR allows users to export the current view including all visible layers to a png file.
=> export current view to png

src/renderer/clipboard.js
This PR enables the keyboard shortcut ```CTRL-A``` for all non-OSX platforms. We already handle ```CUT, COPY, PASTE``` correctly but select all did not work on Windows.
=> enable CTRL-A for all non-OSX platforms

src/main/bootstrap.js
When running on Windows 10 Electron does not fire the ```ready-to-show``` event. Within the handler for this event we persisted the recent project settings. Since the settings did not get persisted we created a new 'untitled project' on every startup.
This PR fixes the issue by ignoring the ```ready-to-show``` event and waiting for [browserWindow.loadURL(...)](https://www.electronjs.org/docs/api/browser-window#winloadurlurl-options) being resolved. In fact this is the same as handling the [did-finish-load](https://www.electronjs.org/docs/api/web-contents#event-did-finish-load) event.
=> replace ready-to-show event with await

src/i18n/de/electron.json, src/i18n/en/electron.json, src/main/bootstrap.js, src/main/ipc/save-file-dialog.js, src/main/ipc/share-layer.js, src/main/ipc/share-project.js, src/renderer/components/layerlist/Actions.js, src/renderer/ipc.js, src/renderer/map/Map.js, src/renderer/map/interaction/drop-import.js, src/renderer/project/input-layers.js
PR introduces the ability to export a layer to the filesystem. Exporting is done via the Layers panel. Select a layer and choose the ```share``` action button. This also closes #311 (missing i18n key for exportProject.title).
=> import layer (drag-and-drop) from and export layer to filesystem

package-lock.json, package.json, src/i18n/de/web.json, src/i18n/en/web.json, src/renderer/components/Activities.js, src/renderer/components/SIDC.js, src/renderer/components/feature-descriptors.js, src/renderer/components/feature-descriptors.json, src/renderer/components/palette/FeatureList.js, src/renderer/components/palette/FeaturePalette.js, src/renderer/components/palette/Presets.js, src/renderer/components/palette/Search.js
This PR switches the symbol palette default from showing no symbols to showing all symbols. We use the power of [lunr](https://lunrjs.com) to do a full search in the symbol descriptions and (optional) tags.
=> 0.6.0/lunr

package-lock.json, package.json
The following was not transpired correctly with the previous versions of webpack and babel:
```
const { filter = DEFAULT_FILTER, presets = DEFAULT_PRESETS } = memento || {}
```
=> updated babel and webpack to fix transpile errors

src/renderer/components/layerlist/Actions.js
The ```Actions``` component now handles changes to the active layer correctly and disables the "delete layer" action accordingly.
=> handle changes to the active layer correctly (fixes #340)

src/i18n/de/web.json, src/i18n/en/web.json, src/main/bootstrap.js, src/renderer/components/Activities.js, src/renderer/components/basemap/Name.js, src/renderer/components/basemap/SourceDescriptorDetails.js, src/renderer/index.css, src/renderer/map/Map.js, src/renderer/map/basemap/tileSources.js
In order to follow the guidelines for the usage of publicly available map sources this PR introduces the attribution property for (base)map sources (see #371).
We also follow the commonly used place in the lower right corner of the map to show the attributions. ODIN allows multiple maps to be visible so the attributions auf all visible maps are combined:
Since attributions often require users to include links to the data sources we also allow http(s) links. These links are clickable but instead of opening them in ODIN we forward the requests to the system's default browser.
This may affect future features since forwarding is down by hijacking the ```will-navigate``` and ```new-window``` events of electron's webcontent and prevents their default behavior.
=> feature attribution

package-lock.json, package.json, src/renderer/components/basemap/Name.js
Since everything that is put into the attributions property of a basemap will get displayed by the OL attributions control it needs to get sanitized. This PR introduces the [DOMPurify library](https://github.com/cure53/DOMPurify) in order to limit attributions to a ```<a>``` tag with a single ```href``` attribute.
=> sanitized basemap attributions

src/i18n/de/web.json, src/i18n/en/web.json, src/renderer/components/Activities.js, src/renderer/components/settings/SliderSetting.js, src/renderer/components/settings/SwitchSetting.js, src/renderer/components/settings/util.js, src/renderer/map/Map.js, src/renderer/map/style/default-style.js, src/renderer/map/style/labels-polygon.js, src/renderer/map/style/line-labels.js, src/renderer/map/style/multipoint-style.js, src/renderer/map/style/polygon-labels.js, src/renderer/map/style/symbol-style.js, src/renderer/project/io.js, src/renderer/project/preferences.js
User do now have control about some aspects of the styling of tactical symbols. They can
* change color preset (light, medium, dark)
* change the line width of tactical graphics, boundaries, areas, ...
* change the font size and weight for labels of lines, areas, ...
* change the size of symbols with point geometry and the size of the symbol label
* enable sizing based on the echelon
* choose between simple and extended status of point based symbols
=> user influenceable styling for tactical symbols

src/renderer/map/style/corridors/G_T_R.js
The text "RIP" is now displayed inside the symbol and no longer on the top line (according to MILSTD-2525/App6).
=> Correction place of text in task "RIP"

src/renderer/components/feature-descriptors.json
For following EMS symbols the properties have been changed from Installation to Equipment:
- ATM
- Control Valve
- Discharge Outfall
These are listed in MILSTD-2525C in infrastructure section, but the tactical symbol corresponds to those of equipment.
=> Change Properties for 3 EMS "Equipment" symbols
